-- AlterTable: Class
ALTER TABLE "Class" DROP COLUMN IF EXISTS "type";
ALTER TABLE "Class" DROP COLUMN IF EXISTS "active";
ALTER TABLE "Class" ADD COLUMN IF NOT EXISTS "slug" TEXT;
ALTER TABLE "Class" ADD COLUMN IF NOT EXISTS "ageGroup" TEXT;
ALTER TABLE "Class" ADD COLUMN IF NOT EXISTS "fee" INTEGER;
ALTER TABLE "Class" ADD COLUMN IF NOT EXISTS "teacher" TEXT;
ALTER TABLE "Class" ALTER COLUMN "schedule" DROP NOT NULL;

-- AlterTable: Registration
ALTER TABLE "Registration" DROP COLUMN IF EXISTS "classType";
ALTER TABLE "Registration" DROP COLUMN IF EXISTS "studentName";
ALTER TABLE "Registration" DROP COLUMN IF EXISTS "parentName";
ALTER TABLE "Registration" DROP COLUMN IF EXISTS "age";
ALTER TABLE "Registration" DROP COLUMN IF EXISTS "message";

ALTER TABLE "Registration" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "Registration" ADD COLUMN IF NOT EXISTS "notes" TEXT;
