-- AlterTable
ALTER TABLE "GalleryItem" DROP COLUMN IF EXISTS "description";
ALTER TABLE "GalleryItem" DROP COLUMN IF EXISTS "featured";
ALTER TABLE "GalleryItem" ALTER COLUMN "title" DROP NOT NULL;
ALTER TABLE "GalleryItem" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
